#!/bin/bash											
while true																					#thats the wa to go
do echo -ne "$i"'\c'																#no idea what das stuff does
cols=$( tput cols )																	#fancy nice looking things
rows=$( tput lines )																#fancy nice looking things
welco_message="Test Test $(date)"										#variables must be called in the while loop
message=$welco_message															#
input_length=${#message}														#
half_input_length=$(( $input_length / 2 ))					#
middle_row=$(( $rows / 2 ))													#
middle_col=$(( ($cols / 2) - $half_input_length ))	#
tput clear																					#	
tput cup $middle_row $middle_col										#
tput bold																						#
echo $message																				#
tput sgr0																						#
tput cup $( tput lines ) 0													#

sleep 0.5																						#
clear																								#
done																								#

